---
title: "Árboles de Decisión VS Red Neuronal"
subtitle: "Crabs Dataset"
author: "Escalada Christian"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: hpstr
    highlight: vignette
---

# Parte I - Preprocesamiento

```{r}
# Cargamos Librerías:
library(MASS)
library(caret)

# Cargamos Dataset:
data(crabs)

# Preprocesamos Dataset:
crabs$index=NULL
crabs$sex=NULL

# Creo partición al 70% - 30% y asigno semilla.
set.seed(123) ; particion= createDataPartition(y=crabs$sp, p=0.7, list=FALSE)
entreno= crabs[particion,]
testeo= crabs[-particion,]

```
 
```{r}
# Mostramos el Dataset:

head(crabs)
```
 
# Parte II - Árbol de Decisión.
 
```{r}
# Cargamos Librerías:
library(rpart)
library(rpart.plot)

# creamos un AdD:
arbol=rpart(sp~.,entreno,method="class")

# Graficamos el AdD:
rpart.plot(arbol,extra=1,type=5,cex=1)

# Ingresamos un Cangrejo Nuevo:
Cn=data.frame(FL=2,RW=0.5,CL=2,CW=1,BD=1)

# Predecimos Cangrejo nuevo:
pred_Cn_AdD=predict(arbol,Cn, type="class")
pred_Cn_AdD

# Testeamos el modelo:
pred_AdD=predict(arbol,testeo,type="class")

# Armamos la Matriz de Confusión:
confusionMatrix(pred_AdD,testeo$sp)
```
 
# Parte III - Red Neuronal.

```{r}
# Importamos Librerías:
library(nnet)
library(NeuralNetTools)

# creamos una RN:
red=nnet(sp~.,entreno,size=10,maxit=10000)

# Graficamos la RN:
plotnet(red,
        circle_col = "darksalmon",  
        pos_col = "pink",
        neg_col = "grey",
        bord_col = "darkred",
        circle_cex=5,
        alpha_val=1,
        cex_val=1,
        cex=15,
        max_sp= TRUE)

# Ingresamos un Cangrejo Nuevo:
Cn=data.frame(FL=2,RW=0.5,CL=2,CW=1,BD=1)

# Predecimos Cangrejo nuevo:
pred_Cn_red = predict(red,Cn, type="class")
pred_Cn_red

# Testeamos el modelo:
pred_red=predict(red,testeo,type="class")

# Armamos la Matriz de Confusión:
confusionMatrix(factor(pred_red),testeo$sp)

```

# Parte IV - Comparación:

|Modelo       |Accuracy     |Sensibilidad |Especificidad|
|:------------|:-----------:|:-----------:|:-----------:|
|AdD          |0.8833       |0.8333       |0.9333       |
|RN           |0.9833       |0.9667       |1.0000       |


* Podemos observar que en este ejercicio, la **RN** tiene una mejor Performance respecto a AdD, por lo tanto sus predicciones son mas confiables.

# Bibliografia:

[Pretty Docs](https://github.com/yixuan/prettydoc/)

# Muchas Gracias!
 
 
 
 
 
 
 
 
 